### ISSUE TITLE
Register Page (Dummy)

### ISSUE THREAD

**Issue by cqvu** [os-ucsd/chausters#10]
## Tasks
- [x] Create a Register.js component in client/routes
- [ ] Add a /register route to App.js with react-router
- [x] Create the Register page according to the screen in Figma (attach below)

## Acceptance Criteria
- Going to [url]/register routes to the Register component
- Register page should look like this (attach Figma screenshot):
 
## Resources
- http://www.hackingwithreact.com/read/1/22/how-to-add-a-new-route-to-react-router
