### ISSUE TITLE
Set up default routes and react-router

### ISSUE THREAD

**Issue by cqvu** [os-ucsd/chausters#15]
## Tasks
- [x] `npm install --save react-router-dom` (in client)
- [ ] Create a new directory `routes` in client (client/routes)
- [ ] Create a few default component routes (Login, Register, Main)
- [x] Add routes to created components in App.js

## Acceptance Criteria
- React-router is installed (and added to package.json through --save)
- Routing works

## Resources
- https://www.freecodecamp.org/news/react-router-in-5-minutes/
