### ISSUE TITLE
Boilerplate Repository Structure

### ISSUE THREAD

**Issue by cqvu** [os-ucsd/chausters#4]
## Tasks
- [ ] Set up directory structure (frontend, backend, docs, etc...)
- [ ] Initialize React app for frontend
- [ ] Initialize Node app for backend

## Acceptance Criteria
- React app and Node is initialized
- Repository contains different directories

## Resources
- https://github.com/jaewonhimnae/boilerplate-mern-stack
