### ISSUE TITLE
Set up MongoDB

### ISSUE THREAD

**Issue by cqvu** [os-ucsd/chausters#9]
## Tasks
- [ ] Set up a database on Mongo Atlas
- [ ] Set up mongoose
- [ ] Connect Atlas with our Node app with mongoose

## Acceptance Criteria
In the Node app, console.log something when connection to the database is established

## Resources
- https://www.mongodb.com/
- https://kb.objectrocket.com/mongo-db/simple-mongoose-and-node-js-example-1007
